apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
    namespace: default
stringData:
    config.toml: ENC[AES256_GCM,data:ucjUFNaO4zEmmpXUj0c7ClFyTVvKVlpXd0RmsnTrO0hERD4Yv87yrJDhKGj8F27W+b4rQ3FfRavQD1r+Xby4vlQ8i3sNE0Z6N+kxlw2IVErpkeI+xlqgdW9x/y8h/vvUr30iHfXdoEXk6d8bzQG76TK/h9RDJltJRbT2W8jBUEn6tiOmJQJmxuVQX45uvI2EE1+Vj12GZmpj6yO3IMGyFeiF8y+Xg+1m409xTdws2PxpYqkmEM++6v9+7ZyLPpcbM7dNshCgg8RpNFoPKoVRkoN1MVi6UJEmS0PqZysND1NCTR3xziVUdfvxwKYXYIHy6eJvN98n3rfBmitM15S88gIzLkCmhiuLDxiTfBaqbUbcFRJ7C/lDloRpGLzS3tSMQg==,iv:6nh7aJNLXXhngcM0JypqMlAvTuEJwmlgUalkcE6KKgE=,tag:kzHlK0t/AS+MDPjL/OWDtw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18ffs7t79y4ajp6rggu8qake3fggyjazfq65mt6mkr6hkmgr9s3uqayl7q2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSHNJZWM2RXErdVFuQlFp
            U2Qwbi8xZHNOZ3pWQk5yaTllM3psa3BOaVMwCnVkYnhDM0pDcDBIcEtya1ZFbVNv
            Rlc1SUJ1QnpzMUV0dXY3cGxjZWcydGcKLS0tIGkyKy9tYjl1Nks4ekJEaWJDQnhv
            SGtjclVoRm4wUHY1d2h0Nm5jZ2tDSjgKFvU3t1yOd993l6W56phGJvv5TZv/qmby
            d16e9TfBahi3LAf8in9xV4qYCqC5d59WradOZxXg8q4rvNe5EL1GVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-16T05:18:34Z"
    mac: ENC[AES256_GCM,data:ubXY31wmhBSN7BgXzgU2sLzHA1GR61nStU+Wwoc8yUhEF0wrzxV3OQNmhXwYy2hKi6TeMXdb8PnsCiZT6ksMZgZWvC/p9gIapwso9HfE19Xbn4q41edyxH16sOhfldxnivktqnPiEcIomAeYkymiULSzTnyHuLH76DmIFagVUCw=,iv:FWm5/tVyY8MhofLPwmMQgzrEEPCaE57d3OSbFYRapDk=,tag:fSrnQ9xOoxGyNQmQhL7o9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
