apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: kube-system
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:cK3g60vkFsoxQ2bEiEWKxEP89oHK91Du9VmyrXnMr0L9+6q60K46nzzNrU3aW8wiUQvFQotpQIb9LcEMfuLy91ELQqTcts09hOXs1fEigF0Zi3cFO4izIH4ql+W3vmVMkOlJ86mlZeWCmGJPU4yVdoA272uQnXzu3YA4OE5oeJuqcAMoToynKyHXLJD6x/35uoZ268ikbSqtqCnud79UwwcD6BAiycCuXs7f5oPsq3eqzrgh62sq13h2YCLkEvRJNo3R77dJ3pGbqmOBOKUs57P5CxgdA8swXUxuIUgvtRcpm3AgtQNgZadoR5rQavQNA+5LBz5itCktaLVw3OsypreHDoYE4p1b5U+ecDq1JFr7lEy3NoTKoRpAZ0rpc3PV3/GN42xIs6ouqSJCFdXseeiGHbdT6KaekqFiOLhNNN0Wx/inDkjONAfhcqRcnhmfhp1T0PdFPWO8qwO/onTk7MFzjhi821dWJartfKWkX17d3qnuUS+LZBpGVOoXpJ4CAEfBxPue9Iet5HyViIJVVxjZcLmFu0bhw+hAs9jwM0uBD1pVVD76JKzjUwjDpFf2BKUu6gvMelVStDeXzfTaZKSmn3o2zqUKlKQTWny+/tLFRLgGK5mYkUj5v/AX2puTw/krIZ+4lZb7l+2tCqTYwdj87p/IczV8tq3xI47IT+rCOnND6kh9OmoGAT3MmoUjzwxVd+Dr3KTyRbjj3MfJHRLyFU0+b/eiGOQVgG/HAa7z9rBAKGL6dKHFnyWv1lYuWUww/u+G8zD5GIxqdF7agwX8T4gWTV8CT9vJEhLFErhuujC3w/so7rvXAOAINYQga0Iu9VvxksBGRh1VFNpu6AkWDeaKUzvPOKkhqqQfyLHIWCKQHONcXd6p6D2g27UiQMEDxJhAZ2XD1kwOu9TJ7qEKs8bS8szf+HCUao+1il1ihsk3VaXK1tG02ftbuUAeFr4nvP/Kt7KnTXJRbpRjw2RJa5madNXxK89+fuatjE9ISAqQEEsi6ICyu5W8K+DWyridY7ol0F+xmBk4Sq4feUcRy992IeYVcmWqIAdITqhskObyP2aJ5WjHCnbYStB+G+5SnEKKldHMwXmUtagPUmx8Z1PNmjycPrvbuzhO4mgml+0cplAwmXd+VYDlZ7F7R4ukeVdX8uSA9f8vb3jGkfUd96NtEkGlB7x1p6Y70PjwsFCJ9HdLGTFVOwmsMjFFVYuD/7xuzzC5jvn2OkuJAtmh1QUJqIoSRrUFm8vKau1hBQkFmlXXAWCNb3B00G46Ge2q3kgO+GcvtlTKlGMKWs5DhEGukRhhrf2W0O2wi1+Hpt1ZQyGdOVEPmdP2UFEYWcz01tuLzPYQeURDCpjFrG6qiVxROM50RYbqsqZelyexCSjIUybyBa1SxZO0qjko2ZH3NfDFVWaKVsqOScBV7dZOdP+Kz71cxYtbCX1wBajnA040F2UV/LI=,iv:EAZn2RoN/lolbaRa6RHKJo/FGo9DFH6vojA7N+7dYSs=,tag:9PW5cicN4uUiLvw9ik67Pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18ffs7t79y4ajp6rggu8qake3fggyjazfq65mt6mkr6hkmgr9s3uqayl7q2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTGx0TmNyTXZtR2NGcXNm
            YmswbkpJcDE1Ly9wOEJpVktSSGExR0p6NGd3CjUzMnc5R3ZqV3NmdloyanFEUjJ1
            S1d0eGxRaTlIcWhoaExQMXdQSDdiWTgKLS0tIENSaXdETUs1VTM4c2FJV3BpN3Nt
            RnV6QnF5M2c5VWJHL0h1Vnlnd0tyNW8Kq5f1qe9H6MZ8nufPRTrcWZ6ZU3C0cxKr
            vLL627L1JgOkA9nhVUBAUv58HJglF63ndAQefSRCPRk+eHNbJpUifA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-16T01:40:05Z"
    mac: ENC[AES256_GCM,data:kH5Es5CBy3U9QdmokbNfPsDTzZQfUhUCpeA0O9Zw/RIW/wFz3afTCBM0CBCjcDaSZaqQhgu/54DB9jFer0ItHrYo7MXdqBw1mbD/fUn0atYyZBJq8rEA2kFbb5+kRY2e7WMIhZYXvkX38hevOpaMvnPLJ1QiOmP47LJYKFXLsUw=,iv:ha2I9X5bQphyOc47Ykgxod2QDi9wIHiuMAUbr9gyUag=,tag:BlSVp5tZZos77XgoWIXnmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
