apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:r4oJzNo46A==,iv:tWUOgJG/hg8MRLdtvyThiCaGRJY8ioGwnt2YjblTlrM=,tag:6VZ9FQkt6VhdVKhLMQ5mTA==,type:str]
    admin-user: ENC[AES256_GCM,data:5XbMkeQ=,iv:cMNrGysm5R+hIEx0JqDiECEAeT2+kz0q4Fb3PDAf+0Y=,tag:1uUQwg01CqKKKIvbsac+5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18ffs7t79y4ajp6rggu8qake3fggyjazfq65mt6mkr6hkmgr9s3uqayl7q2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRE1ma1F0bHd6VTlBSXBM
            ZUk2MklkUWJCK0NwR0k2ajR4YzJZbzlEaDMwClFCUXhidk13ZklyMDNHYmhKeDQr
            NlB0UUhDT1YyUnJwa1BxeEQvaGd2R1kKLS0tIGNIVk0xazRscTNoaW9ENkVkQ2Y3
            RkNpQ29PMnZBNnZjZlpSZkEzY0F0TkUKCvyBDRadk8M1qRGu6yc4M9vmwt+VOOcO
            ujPVC6WYTW23KqZ54ShiSNm1S6sOioKEwWT5M8T+knm7R0xAdriGow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-16T05:52:53Z"
    mac: ENC[AES256_GCM,data:vC4roMuA+PeMaez1m5f9YvyGmCVXhHdGQG7ybKvfrXDJt5d+YrkgB0bPrUCypgmX8iceZT/QmMxgkzTifCeV7114EvuBi7PXPhoPX1npH/XTxxFaGH/8rZ/4rK9Vahe9dMytnEoVdrf9K+bOgralrzYPNWbuRFTLJ8DYrUlzl7o=,iv:lK6idadkRFsRRig8vWeD9pTDmy6ptsG5BjCQp+YSTyg=,tag:yozCS1MUKJrVDzyqR0NkUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
