---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: pihole
      version: 2.18.0
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: false
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicaCount: 1
    strategyType: RollingUpdate
    maxSurge: 1
    maxUnavailable: 1
    dnsHostPort:
      enabled: true
      port: 53
    serviceDns:
      mixedService: true
      type: LoadBalancer
      port: 53
      annotations:
        io.cilium/lb-ipam-ips: "192.168.30.53"
        externalTrafficPolicy: Local
    serviceDhcp:
      enabled: false
    serviceWeb:
      http:
        enabled: true
        port: 80
      https:
        enabled: true
        port: 443
      type: LoadBalancer
      annotations:
        io.cilium/lb-ipam-ips: "192.168.30.54"
    virtualHost: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
    ingress:
      enabled: true
      ingressClassName: nginx
      path: /
      hosts:
        - *host
      tls:
        - secretName:
            - hosts:
                - *host
      annotations:
        hajimari.io/icon: mdi:raspberry-pi
        hajimari.io/group: "networking"
        hajimari.io/targetBlank: "true"
        hajimari.io/info: "DNS Server and Ad Blocker"
        cert-manager.io/cluster-issuer: letsencrypt-production
    probes:
      liveness:
        enabled: true
        initialDelaySeconds: 60
        failureThreshold: 10
        timeoutSeconds: 5
        port: http
        scheme: HTTP
      readiness:
        enabled: true
        initialDelaySeconds: 60
        failureThreshold: 3
        timeoutSeconds: 5
        port: http
        scheme: HTTP
    persistentVolumeClaim:
      enabled: true
      existingClaim: pihole-data-pvc
    admin:
      # existingSecret: "pihole-secret"
      # passwordKey: "PIHOLE_ADMIN_PASS"
      adminPassword: HvaqQu.hqoR-W9Nv
    extraEnvVars:
      TZ: "America/Denver"
    DNS1: "1.1.1.2"
    DNS2: "1.0.0.2"
