---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app servicenow-k8s-informer
  namespace: servicenow
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-informer-chart
      version: 2.1.1
      sourceRef:
        kind: HelmRepository
        name: servicenow-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    acceptEula: "Y"
    instance:
      name: drwbwe
      domain: service-now.com
    clusterName: GallagherLab
    instanceCredSecretName: k8s-informer-cred
    podAnnotations:
      secret.reloader.stakater.com/reload: k8s-informer-cred-drwbwe
