---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.4.2
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-init:16
        imagePullPolicy: IfNotPresent
        global.envFrom:
          - secretRef:
              name: authentik-secret
    global.podAnnotations:
      secret.reloader.stakater.com/reload: authentik-secret
    autoscaling:
      server:
        enabled: true
      worker:
        enabled: true
    strategy:
      type: RollingUpdate
    worker:
      strategy:
        type: RollingUpdate
    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      hosts:
        - host: &host authentik.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: *host
    global.envFrom:
      - secretRef:
          name: authentik-secret
    postgresql:
      enabled: false
    redis:
      enabled: false
    geoip:
      enabled: false
    prometheus:
      rules:
        create: true
      serviceMonitor:
        create: true
    authentik:
      email:
        from: id@${SECRET_DOMAIN}
        host: smtp.gmail.com
        port: 465
        use_ssl: true
      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
