---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lidarr
  namespace: flux-system
spec:
  path: ./kubernetes/apps/downloads/lidarr/app
  targetNamespace: downloads
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  commonMetadata:
    labels:
      app.kubernetes.io/name: &appname lidarr
  prune: true
  wait: false
  interval: 10m
  dependsOn:
    - name: cluster-apps-csi-driver-nfs
    - name: cluster-apps-external-secrets-stores
    - name: cloudnative-pg-cluster
