apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:T4GfOmpD703xPIEN7cvh2mLyTilhI3I=,iv:E0VbvILOS4Jyn1oICVHFUKdTUg9KcmtNCCHMt+ejCsI=,tag:jI4Nvk2w25SqaKjkJRW2og==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:3hd6REEkmJJNSvUBFy8RnKl9zR0bnoZd0UQcHkYPC7ueB+Ks,iv:kBHlOft5BPdq9HeaSHXHvk42BBlpUKIsjy5AZUDbifA=,tag:WKfk+E4uofpN8U6N1Llzbw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:zRvZZiv+3u6YvkdMoiEWGMg=,iv:vSpRmOCp5igM05iWys72pcu64lCeQ+1rLiJ4MovfC6k=,tag:2Prl+iSfrqzQdxWqGKo3Sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18ffs7t79y4ajp6rggu8qake3fggyjazfq65mt6mkr6hkmgr9s3uqayl7q2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV0VXNFZveU0vS093N2Zm
            OUFwRG1uZW8zVDVIMlI1c1BnS2VUa1pnQVcwCm1mdW9FSG5HQ2pqbkJyZlpMUmpN
            T3JCKzkzWElRdHQvVTZ2MHdUS1dJdmMKLS0tIHV4dmcyMGo5alZObU9ZYVRQNGNm
            K1NMT24zSWlGTGF1TnY4ZGpBQ2tTNUEKqSUVq1D6xbT9mH/K2p1srLBhZNBuHFFE
            4Ozy6zPceXT6NvvQiubw1D/ktcDeaNw6PKjGpl0yq4FX6xf8Jmel1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-16T05:18:29Z"
    mac: ENC[AES256_GCM,data:Ls1ofz9mfSGLdKBPPb3SzmxDNM4X2at9vx7EaOdgsHs4nouZCG+CPTW0G60yV7tyetu0BAJTkpo0xVCkpB4o49b22Dqp3Ht8RegDORT86LalQQNqhbx75cJ1fIlIfCZaBV+ncQ/yAd4SDQTHKIwLUcOOTJau/ogT2ypQCLyR+7o=,iv:6q3rPdDmfzYG5+NlCpmYhDubqWZXoOPuefy9Up8WMMk=,tag:JgUOKefbP/Ue0k67lNCYsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
