---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  dependsOn:
    - name: intel-device-plugin-gpu
      namespace: kube-system
  values:
    controllers:
      plex:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 50Gi
              storageClass: k8s-config
              globalMounts:
                - path: /config

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 105
              - 109
              - 65539

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: rolling
            env:
              PLEX_PREFERENCE_1: "allowedNetworks=192.168.1.1/24,192.168.30.1/24"
            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 100m
                memory: 8G
              limits:
                gpu.intel.com/i915: 1
                memory: 12G

    service:
      app:
        controller: plex
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.30.155
        ports:
          http:
            port: 32400

    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        className: external
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: 32400
        tls:
          - hosts:
              - *host

    persistence:
      media:
        type: persistentVolumeClaim
        existingClaim: glabmediaclaim
        globalMounts:
          - path: /media
      transcode:
        type: emptyDir
        globalMounts:
          - path: /transcode
