---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-config
  namespace: database
  labels:
    app.kubernetes.io/name: &name pgadmin
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-config
  resources:
    requests:
      storage: 1Gi
