---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-sonarr
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-csi-driver-nfs
    - name: cluster-apps-external-secrets-stores
    - name: cloudnative-pg-cluster
  path: ./kubernetes/apps/downloads/sonarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
