apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:FfxJeU2XWGuL/lYNj9F+DYNWkNoGble0m1dd49KPaetSRF1y,iv:aQzlL/2t+Fu7I7/KUTkYapKPm5D7BqMl1iGx1GGLoIA=,tag:sg2uiZbo4tAsl3C7nIuBNA==,type:str]
    credentials.json: ENC[AES256_GCM,data:h4bF9IvGbn/2k4rqm54JCVZNUXCvHViFy1zGWATqre6S4GzJfyxArgijasad+pz2nZtYxsxrbm6xjBiDd4BSw7LzhHvqKbyohJ4FbTJcd3Z9Zd1FVJQZlOqw2C5x7nPQxfN+iTgQD7ndMPWyBhfpGrGx9UTbMeHEEpYwkw/PSMrUY2al2M6OHH7xsz/6xlbpKReAXWYYIDfKY3TFOprg+7dGuHzvfa6v4B6GQM7g+w==,iv:2bmXoYVb7TicN1q8/blOeg1pYFpA0rUgaRDjF8Z5mMA=,tag:2RksudGJK4wi/09qhxw0lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18ffs7t79y4ajp6rggu8qake3fggyjazfq65mt6mkr6hkmgr9s3uqayl7q2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMU9rR2ZSa09yY1d1NUts
            YXdiU0JJZFluYjVpR3AyNktpN2VTeC9FRXhBClY2ZnVGelZITk9wL1VoS3Z6eXFQ
            VFR2TnQyMS94MHA0YUZYV0tCRXhQRmcKLS0tIEpIcDhmajFWTStmK3VuSy9xLzhF
            YjNOMEwxaVE0cFpUbUhERnVaNXozdFkKepw1OdDRAJWCqe3lvAnLQWtX/QpUiaZK
            lZ6dusdCjpyRtFWEBnB4Dnzf8MZssAxaNo71pMgwVvqO1BPJeHEqbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-16T06:54:19Z"
    mac: ENC[AES256_GCM,data:NLoFIljYeqP5eL6+CnVqyNTNWVqD/bTqJChDBI2t/kzr2zckpgcEq6r7O55k4l550qwcA887ndpRlh6TPtD1QsEjin8Gid952gQi/baweQoUgt+Hn9YTLkTvcZRiNeJUH7KiTI0BxCgBYT+gizPiPGoX75VdMcrSFWn9dcJNk+Q=,iv:Q+aIl15zrFWYVoebl/ZWTpA4kaEqDuMKlHvC10By6fk=,tag:R1JxqGjKlduSXU0lAqCO6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
